### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by dlsnet** [cvonk/OPNpool#14]
It is not possible to build the project on the current version of esp-idf as too many dependencies fail. Is there any chance that you update the project? (But, of course, there is a good chance that I'm doing something wrong)

**Comment by dlsnet** [comment]
[{
	"resource": "/c:/opnpool/OPNpool/interface/components/factory_reset_task/src/factory_reset_task.c",
	"owner": "cpp",
	"severity": 8,
	"message": "esp_event.h: No such file or directory",
	"startLineNumber": 21,
	"startColumn": 10,
	"endLineNumber": 21,
	"endColumn": 10
},{
	"resource": "/c:/opnpool/OPNpool/interface/components/ota_update_task/src/ota_update_task.c",
	"owner": "cpp",
	"severity": 8,
	"message": "driver/gpio.h: No such file or directory",
	"startLineNumber": 28,
	"startColumn": 10,
	"endLineNumber": 28,
	"endColumn": 10
},{
	"resource": "/c:/opnpool/OPNpool/interface/components/wifi_connect/src/wifi_connect.c",
	"owner": "cpp",
	"severity": 8,
	"message": "esp_wifi.h: No such file or directory",
	"startLineNumber": 20,
	"startColumn": 10,
	"endLineNumber": 20,
	"endColumn": 10
},{
	"resource": "/c:/espressif/esp-idf/components/spi_flash/include/esp_spi_flash.h",
	"owner": "cpp",
	"severity": 4,
	"message": "#warning esp_spi_flash.h is deprecated, please use spi_flash_mmap.h instead",
	"startLineNumber": 6,
	"startColumn": 2,
	"endLineNumber": 6,
	"endColumn": 2
}]

**Comment by cvonk** [comment]
What about using the suggest ESP version?

Op di 30 mei 2023 02:14 schreef dlsnet ***@***.***>:
