### ISSUE TITLE
Use with Intelliflo pump without pool controller?

### ISSUE THREAD

**Issue by dronenb** [cvonk/OPNpool#15]
Hi, just curious, is it possible to use OPNpool with only the Intelliflo VS pump?

**Comment by cvonk** [comment]
Unfortunately, it requires a pool controller.  I designed as such, so the
system can still function without the OPNpool Interface.

/C

Op vr 16 jun. 2023 03:40 schreef dronenb ***@***.***>:

**Comment by cvonk** [comment]
Issue answered.  Inactivity.  Closing.
