### ISSUE TITLE
error trying to clone

### ISSUE THREAD

**Issue by justlikeef** [cvonk/OPNpool#4]
Running clone through HTTPS: git clone --recursive https://github.com/cvonk/OPNpool.git

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:cvonk/OPNpool_provisioning.git' into submodule path 'C:/Users/justl/Documents/Projects/OPNpool/android' failed
Failed to clone 'android' a second time, aborting

Running clone through SSH: git clone --recursive git@github.com:cvonk/OPNpool.git

Cloning into 'OPNpool'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by cvonk** [comment]
Make sure you have ssh set up, or clone using https as usual, and add the
--recursive switch

Cheers
/C

**Comment by justlikeef** [comment]
Both are set up and I'm getting a permission error both ways.  You can see that I've used the recursive switch on both commands. in my comment.

It seems to be something specific to the Android client.  If I do a "git rm android" then "git submodule foreach "(git checkout master; git pull)&"" the other submodules pull OK.

**Comment by cvonk** [comment]
I am traveling with just a phone, so either can't try it

**Comment by martinbogo** [comment]
Some more info -- failure to clone ( android ) 

`Cloning into '/Users/martin/Development/OPNpool/android'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:cvonk/OPNpool_provisioning.git' into submodule path '/Users/martin/Development/OPNpool/android' failed
Failed to clone 'android' a second time, aborting`

**Comment by cvonk** [comment]
You need to setup SSH authentication first, it clone using HTTPS.

/C

**Comment by cvonk** [comment]
Inactivity. Solution proposed.  Closing
